export const NEW_SEARCH_USER = 'NEW_SEARCH_USER';
export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST';
export const USER_SEARCH_SUCCES = 'USER_SEARCH_SUCCES';
export const USER_SEARCH_FAILURE = 'USER_SEARCH_FAILURE';
export const UPDATE_FILTERS_FORM = 'UPDATE_FILTERS_FORM';
